"""The landscape read for you: who leads, at what cost, and what that means.

The landscape puts every candidate's trials side by side, arm by arm. That is the
evidence, and it takes a reader several minutes to turn fifty arms into an answer. This
turns it into the answer first:

- **One measure.** The endpoint the most candidates posted against a comparator, which
  is the fairest common ground the registry offers for the disease.
- **One number per drug.** Each drug's best arm on that measure, as its difference from
  the comparator in its own trial.
- **Which way is better, read from the data.** Lower is better for body weight and
  higher for survival, and nothing in a registry says which. Drugs are built to beat their
  comparators, so the direction most drug arms moved is taken as the direction of
  benefit, and the verdict says so.
- **The cost.** The extra share of people who stopped for side effects against the same
  trials' controls, and any FDA boxed warning.
- **A verdict in plain words**, each line with what it means for a reader, generated by
  rules from these numbers and nothing else.

Every comparison here crosses trials, whose populations, durations and background
therapy differ. The verdict says "in its own trial" and "a signal, not a head-to-head
result" because that is what it is.
"""

from __future__ import annotations

import re
import statistics

import landscape as L

MIN_PARTICIPANTS = 100      # a tolerability call on fewer people is noise
SMALL_ARM = 50              # an arm this small is flagged, not dropped


def _endpoint_title(title: str) -> str:
    """The measure in running text: the time point out, lower case, acronyms kept."""
    core = L._TIME_WORDS.sub(" ", title or "")
    core = re.sub(r"\b(from baseline|baseline)\b", " ", core, flags=re.I)
    core = re.sub(r"\s+", " ", core).strip(" ,;:-")
    words = [w if (sum(ch.isupper() for ch in w) > 1 or re.search(r"\d", w)) else w.lower()
             for w in core.split()]
    return " ".join(words) or "the measure"


def _unit_words(unit: str | None) -> str:
    u = (unit or "").lower()
    if "percent" in u or "%" in u or "percentage" in u:
        return "percentage points"
    return u or "units"


def direction(rows: list[dict]) -> int | None:
    """-1 where lower is better, +1 where higher is, None where the arms do not say."""
    deltas = [r["delta"] for r in rows if r.get("delta") is not None and r.get("arm_is_drug")]
    if not deltas:
        deltas = [r["delta"] for r in rows if r.get("delta") is not None]
    if not deltas:
        return None
    mid = statistics.median(deltas)
    if abs(mid) < 1e-12:
        return None
    return -1 if mid < 0 else 1


def best_arms(group: dict, sign: int | None) -> list[dict]:
    """Each drug's best arm on the measure, ranked best first. Arms the drug is named in
    are preferred; an arm labelled only by letter counts where the drug has no named one."""
    by_drug: dict = {}
    for r in group["rows"]:
        if r.get("delta") is None:
            continue
        by_drug.setdefault(r["asset_id"], []).append(r)
    out = []
    for aid, rows in by_drug.items():
        named = [r for r in rows if r.get("arm_is_drug")] or rows
        pick = max(named, key=lambda r: (r["delta"] * (sign or 1)))
        benefit = pick["delta"] * (sign or 1)
        flags = []
        if pick.get("n") is not None and pick["n"] < SMALL_ARM:
            flags.append(f"small arm (n={pick['n']})")
        if pick.get("reference_kind") and pick["reference_kind"] != "placebo":
            flags.append(f"against an active {pick['reference_kind']}")
        out.append({**pick, "benefit": benefit, "flags": flags,
                    "arms": len(rows), "trials": len({r["nct_id"] for r in rows})})
    out.sort(key=lambda r: -r["benefit"])
    return out


def pick_endpoint(groups: list[dict], key: str | None = None) -> dict | None:
    if key:
        hit = next((g for g in groups if g["key"] == key), None)
        if hit:
            return hit

    def drugs_with_delta(g):
        return len({r["asset_id"] for r in g["rows"] if r.get("delta") is not None})
    ranked = sorted(groups, key=lambda g: (-drugs_with_delta(g), -len(g["rows"])))
    return ranked[0] if ranked and drugs_with_delta(ranked[0]) else None


def _boxed_headline(text: str, names=()) -> str:
    """The warning's own heading ("RISK OF THYROID C-CELL TUMORS"), in sentence case.
    A label sets the heading in capitals before the prose; where it has none, the first
    clause of the prose stands in."""
    body = re.sub(r"^\s*(BOXED\s+)?WARNINGS?\s*:?\s*", "", text or "", flags=re.I)
    words = []
    own = {re.sub(r"[^a-z]", "", n.lower()) for n in names if n}
    for w in body.split():
        bare = re.sub(r"[^A-Za-z]", "", w)
        # The heading ends where the prose starts, where a second "WARNING:" repeats it,
        # or where the label names the drug itself in capitals ("SYMLIN", "TRODELVY").
        if bare.upper() == "WARNING" or w.endswith(":") or bare.lower() in own:
            break
        if bare and bare.isupper() and (len(bare) > 1 or w in ("A",)):
            words.append(w)
        elif words and w in ("and", "or", "of", "&"):
            words.append(w)
        else:
            break
    if len(words) >= 2:
        head = " ".join(words).strip(" ,;:")
        head = head.lower()
        head = re.sub(r"\b(c-cell|gi|ild|hiv|cns|qt|pml)\b",
                      lambda m: m.group(1).upper() if m.group(1) != "c-cell" else "C-cell", head)
        return head[:1].upper() + head[1:]
    first = re.split(r"(?<=[.;])\s", body.strip(), maxsplit=1)[0]
    return (first[:80].rsplit(" ", 1)[0] + "...") if len(first) > 80 else first


def _versus(row: dict) -> str:
    kind = row.get("reference_kind")
    if kind == "placebo":
        return "placebo"
    arm = (row.get("reference_arm") or "").strip()
    return (f"its comparator ({arm})" if arm and len(arm) <= 40 else "its comparator")


def _article(pct: float) -> str:
    """'an' before 8, 11, 18 and the eighties, 'a' otherwise."""
    lead = f"{pct:.0f}"
    return "an" if lead.startswith("8") or lead in ("11", "18") else "a"


# Target names as a reader says them. ChEMBL writes the protein's full name, which is
# right for a database and too long for a legend.
_SHORT = (("Glucagon-like peptide 1", "GLP-1"), ("Gastric inhibitory polypeptide", "GIP"),
          ("Glucose-dependent insulinotropic polypeptide", "GIP"),
          ("Programmed cell death protein 1", "PD-1"),
          ("Programmed cell death 1 ligand 1", "PD-L1"),
          ("Epidermal growth factor receptor erbB1", "EGFR"),
          ("Receptor protein-tyrosine kinase erbB-2", "HER2"),
          ("Vascular endothelial growth factor A", "VEGF-A"),
          ("Vascular endothelial growth factor receptor 2", "VEGFR2"),
          ("Cytotoxic T-lymphocyte protein 4", "CTLA-4"),
          ("Tumor necrosis factor", "TNF"), ("Interleukin-", "IL-"),
          ("Sodium/glucose cotransporter 2", "SGLT2"), ("Dipeptidyl peptidase 4", "DPP-4"),
          ("receptor agonist", "agonist"), ("receptor antagonist", "antagonist"),
          (" [EPC]", ""), (" [MoA]", ""))


def mechanism_label(cand: dict) -> str | None:
    """One short name for what a drug does, joining a dual mechanism: tirzepatide is
    'GIP + GLP-1 agonist', not whichever of its two receptors ChEMBL lists first."""
    mechs = [m["value"] for m in (cand.get("mechanisms") or [])][:2] or \
        (cand.get("classes") or [])[:1]
    if not mechs:
        return None
    short = []
    for m in mechs:
        for a, b in _SHORT:
            m = m.replace(a, b)
        short.append(m.strip())
    short = sorted(dict.fromkeys(short))
    if len(short) == 2:
        a, b = short
        for tail in (" agonist", " antagonist", " inhibitor"):
            if a.endswith(tail) and b.endswith(tail):
                return f"{a[:-len(tail)]} + {b[:-len(tail)]}{tail}"
        return f"{a} + {b}"
    return short[0]


def _num(x, digits=1):
    return f"{x:,.{digits}f}"


def _bottom_line(cards: list[dict], land: dict) -> dict:
    """The verdict in one sentence, from the cards below it."""
    by = {c["kind"]: c for c in cards}
    parts = []
    if "efficacy" in by:
        parts.append(f"{by['efficacy']['lead']} shows the biggest effect on "
                     f"{by['efficacy']['measure']}")
    if "tolerability" in by:
        easy = by["tolerability"]["headline"].split(" easiest")[0]
        parts.append(f"{easy} is the easiest to stay on")
    if "warnings" in by:
        parts.append(f"{by['warnings']['headline'].split(' of ')[0]} drugs carry an FDA boxed "
                     "warning")
    if "stage" in by:
        parts.append(f"{by['stage']['headline'].split(' in ')[0]} drugs are in Phase 3")
    text = "; ".join(parts) + "." if parts else "Not enough posted results to call a leader."
    name = (land.get("indication") or {}).get("name") or "this indication"
    return {"kind": "bottom_line", "title": f"Bottom line in {name.lower()}",
            "headline": text[:1].upper() + text[1:], "detail": "",
            "meaning": ("Each part rests on the card below it. Leaders are read from separate "
                        "trials, so treat them as the drugs to look at first, not as a "
                        "ranking a head-to-head trial would confirm.")}


def overview(land: dict, endpoint_key: str | None = None) -> dict:
    cands = {c["asset_id"]: c for c in land.get("candidates") or []}
    safety = {s["asset_id"]: s for s in land.get("safety") or []}
    groups = land.get("endpoints") or []
    group = pick_endpoint(groups, endpoint_key)
    cards: list[dict] = []
    points: list[dict] = []
    ranked: list[dict] = []
    sign = None
    measure = None

    if group:
        sign = direction(group["rows"])
        ranked = best_arms(group, sign)
        measure = _endpoint_title(group["title"])
        units = _unit_words(group["unit"])
        for r in ranked:
            c = cands.get(r["asset_id"]) or {}
            s = safety.get(r["asset_id"]) or {}
            wd, wd_c = s.get("withdrawn_rate"), s.get("placebo_withdrawn_rate")
            excess = (wd - wd_c) if (wd is not None and wd_c is not None
                                     and (s.get("participants") or 0) >= MIN_PARTICIPANTS) else None
            points.append({
                "asset_id": r["asset_id"], "name": r["name"], "ticker": r["ticker"],
                "benefit": r["benefit"], "dropout_excess": excess,
                "mechanism": mechanism_label(c),
                "stage": c.get("stage"), "boxed": bool(c.get("boxed_warning")),
                "weeks": r.get("weeks"), "n": r.get("n"), "phase": r.get("phase"),
                "nct_id": r["nct_id"], "arm": r["arm"]})
        if ranked:
            top = ranked[0]
            better = ("lower" if sign == -1 else "higher") if sign else None
            vs = _versus(top)
            detail = (f"{top['name']} ({top['ticker']}) beat {vs} by "
                      f"{_num(abs(top['delta']))} {units} on {measure}"
                      + (f" over {top['weeks']:.0f} weeks" if top.get("weeks") else "")
                      + (f", in a {top['phase']} trial" if top.get("phase") else "")
                      + (f" with {top['n']:,} people on that dose" if top.get("n") else "")
                      + ".")
            if top["flags"]:
                detail += f" Read with care: {', '.join(top['flags'])}."
            runner = ranked[1] if len(ranked) > 1 else None
            if runner:
                detail += (f" Next best: {runner['name']} ({runner['ticker']}), "
                           f"{_num(abs(runner['delta']))} {units} better than "
                           f"{_versus(runner)}.")
            meaning = (f"Of the {len(ranked)} drugs that posted this measure against a "
                       f"comparator, {top['name']} showed the largest benefit in its own trial. "
                       + (f"Here {better} is better, which is the way most drugs moved it. "
                          if better else "The drugs did not agree which way is better, so "
                          "the ranking reads size of effect only. ")
                       + "The trials differ in who they enrolled and for how long, so this "
                       "is a strong signal, not a head-to-head win.")
            cards.append({"kind": "efficacy", "title": "Most effective",
                          "headline": f"{top['name']}: {_num(abs(top['delta']))} {units} "
                                      f"better than {_versus(top)}",
                          "detail": detail, "meaning": meaning,
                          "lead": top["name"], "measure": measure})

    # Tolerability: the extra share who stopped for side effects over the same trials'
    # controls, among drugs with enough people to say.
    tol = [s for s in safety.values()
           if s.get("withdrawn_rate") is not None and s.get("placebo_withdrawn_rate") is not None
           and (s.get("participants") or 0) >= MIN_PARTICIPANTS]
    if len(tol) >= 2:
        tol.sort(key=lambda s: s["withdrawn_rate"] - s["placebo_withdrawn_rate"])
        best, worst = tol[0], tol[-1]
        ex = lambda s: (s["withdrawn_rate"] - s["placebo_withdrawn_rate"]) * 100
        cards.append({
            "kind": "tolerability", "title": "Easiest and hardest to tolerate",
            "headline": f"{best['name']} easiest · {worst['name']} hardest",
            "detail": (f"{best['name']}: {best['withdrawn_rate'] * 100:.1f}% stopped because "
                       f"of side effects against {best['placebo_withdrawn_rate'] * 100:.1f}% "
                       f"on control ({ex(best):+.1f} points). {worst['name']}: "
                       f"{worst['withdrawn_rate'] * 100:.1f}% against "
                       f"{worst['placebo_withdrawn_rate'] * 100:.1f}% ({ex(worst):+.1f} points)."),
            "meaning": ("People stopping a drug for side effects, beyond those who stop on the "
                        "comparator anyway, is the plainest measure of what a benefit costs. "
                        f"Across the {len(tol)} drugs with at least {MIN_PARTICIPANTS} people "
                        "treated, a smaller gap means patients are more likely to stay on it.")})

    warned = [c for c in cands.values() if c.get("boxed_warning")]
    if warned:
        by_head: dict = {}
        for c in warned:
            names = [c.get("name"), c.get("generic")]
            by_head.setdefault(_boxed_headline(c["boxed_warning"], names), []).append(c["name"])
        ordered = sorted(by_head.items(), key=lambda kv: -len(kv[1]))
        items = "; ".join(f"{head.rstrip('.')} ({', '.join(names)})"
                          for head, names in ordered[:4])
        cards.append({
            "kind": "warnings", "title": "FDA boxed warnings",
            "headline": f"{len(warned)} of {len(cands)} drugs carry one",
            "detail": items + ("; and others" if len(ordered) > 4 else "") + ".",
            "meaning": ("A boxed warning is the strongest caution the FDA puts on a label. "
                        "It does not stop a drug selling, but it shapes who gets prescribed it "
                        "and how closely they are monitored.")})

    late = [c for c in cands.values() if c.get("stage") in ("Phase 3", "Phase 2/3")]
    valued = sorted((c for c in cands.values() if not c.get("is_marketed")
                     and (c.get("model") or {}).get("per_share")),
                    key=lambda c: -c["model"]["per_share"])
    if late or valued:
        top_v = valued[0] if valued else None
        detail = (f"{len(late)} drugs are in Phase 3, the last stage before filing"
                  + (f": {', '.join(c['name'] for c in late[:5])}"
                     + (" and others" if len(late) > 5 else "") if late else "") + ".")
        if top_v:
            m = top_v["model"]
            detail += (f" The model values {top_v['name']} most among unapproved drugs, at "
                       f"${m['per_share']:,.2f} per {top_v['ticker']} share"
                       + (f" with {_article(m['pos'] * 100)} {m['pos'] * 100:.0f}% chance of approval"
                          if m.get("pos") is not None else "") + ".")
        cards.append({
            "kind": "stage", "title": "Closest to market",
            "headline": f"{len(late)} in Phase 3",
            "detail": detail,
            "meaning": ("Phase 3 drugs are the ones that can change the market within a few "
                        "years. The value a share is the model's risk-adjusted view for the "
                        "company that owns the drug, so compare it within that company, not "
                        "across companies.")})

    pool = land.get("pool") or {}
    # Only where the forecasts together claim a real share of the pool: an oncology line
    # of therapy claims a sliver of its population and "0% counted once" says nothing.
    if (pool.get("claimants", 0) >= 2 and pool.get("pool")
            and (pool.get("uncrowded_share") or 0) >= 0.01):
        size = (f"{pool['pool'] / 1e6:,.1f}mm" if pool["pool"] >= 1e6
                else f"{pool['pool']:,.0f}")
        cards.append({
            "kind": "crowding", "title": "How crowded it is",
            "headline": f"{pool['claimants']} drugs share {size} patients",
            "detail": (f"Modelled one at a time, the drugs would treat "
                       f"{pool['uncrowded_share'] * 100:.0f}% of patients in "
                       f"{pool.get('peak_year')}; counted once, the pool supplies "
                       f"{pool['crowded_share'] * 100:.0f}%."),
            "meaning": ("Every forecast assumes its own share of the same patients. Where "
                        "those shares add up to more than the patients who exist, each drug "
                        "keeps less than its forecast says, and the Candidates view shows how "
                        "much each keeps.")})

    cards.insert(0, _bottom_line(cards, land)) if cards else None
    return {"ok": True,
            "endpoint": ({"key": group["key"], "title": group["title"], "measure": measure,
                          "unit": group["unit"], "units": _unit_words(group["unit"]),
                          "direction": sign, "drugs": len(ranked)} if group else None),
            "endpoints": [{"key": g["key"], "title": g["title"], "unit": g["unit"],
                           "measure": _endpoint_title(g["title"]),
                           "drugs": len({r["asset_id"] for r in g["rows"]
                                         if r.get("delta") is not None})}
                          for g in groups
                          if any(r.get("delta") is not None for r in g["rows"])],
            "cards": cards, "points": points, "ranked": ranked}
